### PR TITLE
Add search path for all test files. Closes #151

### LINKED ISSUE #151: Failed to pass path of testdata azure
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/nanoseq pipeline documentation](https://nf-co.re/nanoseq/usage)

## Description of the bug

 Missing output file(s) `test-datasets/fast5/barcoded/` expected by process `GET_TEST_DATA`

## Steps to reproduce

Steps to reproduce the behaviour:

1. nextflow run nf-core/nanoseq -profile test,azurebatch -r 1.1.0
2. Missing output file(s) `test-datasets/fast5/barcoded/` expected by process `GET_TEST_DATA`

## Expected behaviour

Should be able to pass the files to the next step

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: Azure
- Executor: Azure Batch

## Nextflow Installation

- Version: 21.10.5.5658

## Container engine

- Engine: Docker

### PR DESCRIPTION
**Pull request by vsmalladi**
Add search path for tests data to fix issue on Azure not getting files. 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by yuukiiwa — CHANGES_REQUESTED** [review]
Thank you for submitting the PR, @vsmalladi! It will be great if you can make sure all the GitHub Actions pass, or not the pipeline won't work on AWS.
Screenshot from 2022-01-01 15-40-12

**Comment by vsmalladi** [comment]
@yuukiiwa  All changes now pass on azure and aws.

**Comment by vsmalladi** [comment]
> Thank you for submitting the PR, @vsmalladi! It will be great if you can make sure all the GitHub Actions pass, or not the pipeline won't work on AWS. Screenshot from 2022-01-01 15-40-12

All fixed now.

**Review by yuukiiwa — APPROVED** [review]
Thank you, @vsmalladi! I have merged it now

**Pull request merged**
