### PR TITLE
Generate minimap2 index only once per genome

### PR DESCRIPTION
**Pull request by lwratten**
Hello!
This is for https://github.com/nf-core/nanoseq/issues/2 
I used channel manipulation to generate only one index per reference genome.
1. Extract genomes from `set` channel
2. `unique()` so we remove duplicates from the channel
3. Run this channel through `minimap2` indexing process
4. Join the `set` channel from the samplesheet to the indexing output via the reference file name
i.e. `[sample, fastq, genome] & [genome, mmi]` --> `[sample, fastq, mmi]`
5. Run though `minimap2` alignment process as per usual

Tested on multiplexed data (will upload it to `test-datasets`) as well as a single fastq file.
Have not tested on iGenomes (would need to be a file object in the set channel for it to work).

Let me know what you think!

Many thanks to contributing to nf-core/nanoseq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/nanoseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/nanoseq)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/nanoseq/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by drpatelh** [comment]
```
Command error:
  .command.sh: line 2: minimap2: command not found
```

Tests are failing @lwratten . You will need to specify the container for this process in `base.config` too.

**Comment by drpatelh** [comment]
I'll have a look at the rest of the logic after I've had a :tea: .

**Comment by lwratten** [comment]
odd, tests running fine locally but travis is saying `minimap2` is not found

**Comment by drpatelh** [comment]
Thanks @lwratten . Looks good to me 😃 Ill merge and then pull to test.

**Pull request merged**
